/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace ImagePackageGenerator.swig {

unsafe partial class Document : ReferenceObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal Document(global::System.IntPtr cPtr, bool cMemoryOwn) : base(PSDParserPINVOKE.Document_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Document obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static Document Create(System.IntPtr data, int size) {
    global::System.IntPtr cPtr = PSDParserPINVOKE.Document_Create(data, size);
    Document ret = (cPtr == global::System.IntPtr.Zero) ? null : new Document(cPtr, false);
    return ret;
  }

  public int GetLayerCount() {
    int ret = PSDParserPINVOKE.Document_GetLayerCount(swigCPtr);
    return ret;
  }

  public Layer GetLayer(int index) {
    global::System.IntPtr cPtr = PSDParserPINVOKE.Document_GetLayer(swigCPtr, index);
    Layer ret = (cPtr == global::System.IntPtr.Zero) ? null : new Layer(cPtr, false);
    return ret;
  }

  public uint GetDepth() {
    uint ret = PSDParserPINVOKE.Document_GetDepth(swigCPtr);
    return ret;
  }

}

}
